### ISSUE TITLE
Getting input using cookie does not work

### ISSUE THREAD

**Issue by natereal** [tjmahr/aoc#2]
Getting the input using the cookie does not work for me. It works when I use the following bash script from my terminal:
```
#!/bin/bash

# Fetches the input, prints to stdout and copies to clipboard.
# This gives both a quick overview of what the input looks like
# and makes it available on ctrl+v for use in the challenge.

if [ -z "$1" ]; then
  echo "Please provide a day number."
  echo "usage: $0 DAY"
  exit 1
fi

if [ -z "$AOC_SESSION" ]; then
  echo "No session token."
  exit 1
fi

URL="https://adventofcode.com/2021/day/$1/input"
curl $URL --cookie "session=$AOC_SESSION" -s | tee >(pbcopy)
```
[source](https://github.com/AxlLind/AdventOfCode2021/blob/main/fetch.sh)

So I know I have the right key. The aoc package is reading the cookie ok too, I think the problem for me is in the following lines:
```
h <- curl::new_handle()
h <- curl::handle_setheaders(h, Cookie = cookie)
r <- curl::curl_fetch_memory(url, handle = h)
```

I noticed the cookie is named "session" in the header of the website source and that's what the curl line from the script above uses. I tried changing the argument in curl::handle_setheaders to 
cookie = cookie
session = cookie
Session = cookie

but none of these worked. I don't know if this problem is specific to me. Any ideas?

**Comment by tjmahr** [comment]
my .aoccookie file has "session=[...]" where [...] is whatever the key is. It is not just the key by itself. Does that help?

**Comment by natereal** [comment]
That works! Brilliant. Thank you for the help!
